function createfigure1(X1, Y1, E1)
%CREATEFIGURE2(X1, Y1, E1)
%  X1:  errorbar x
%  Y1:  errorbar y
%  E1:  errorbar e

%  Auto-generated by MATLAB on 24-Apr-2016 23:14:17

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'HR','Stay'},...
    'XTick',[1 2],...
    'FontWeight','bold',...
    'FontSize',20);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('Choice %');
xlim([0.5 2.5]);
ylim([0 100]);

% Create errorbar
errorbar(X1,Y1,E1,'MarkerSize',10,'MarkerFaceColor',[0 0 0],...
    'MarkerEdgeColor',[0 0 0],...
    'Marker','diamond',...
    'LineStyle','none',...
    'LineWidth',2,...
    'Color',[0 0 0]);

