function createfigure(X1, Y1, E1)
%CREATEFIGURE(X1, Y1, E1)
%  X1:  errorbar x
%  Y1:  errorbar y
%  E1:  errorbar e

%  Auto-generated by MATLAB on 12-Nov-2015 17:28:20

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'XTickLabel',{'Stat','Stat2','Vol'},...
    'XTick',[1 2 3],...
    'FontWeight','bold',...
    'FontSize',20);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.7 3.3]);
box(axes1,'on');
hold(axes1,'on');
xlim([0.5 3.5])


% Create errorbar
errorbar(X1,Y1,E1,'LineWidth',3);

